// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk4fn4YReYknhVgkLEGinPyHgOS7QuaR4',
    appId: '1:772082583953:web:8a9b2495a65b30ba5bb230',
    messagingSenderId: '772082583953',
    projectId: 'taskapp-d74d0',
    authDomain: 'taskapp-d74d0.firebaseapp.com',
    storageBucket: 'taskapp-d74d0.firebasestorage.app',
    measurementId: 'G-Z9X4YGVJ3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9zhxOrWjDUg8dietYFs2GiNPmMec7pTI',
    appId: '1:772082583953:android:4dfd54f2463294b65bb230',
    messagingSenderId: '772082583953',
    projectId: 'taskapp-d74d0',
    storageBucket: 'taskapp-d74d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVIvFX5021PAViqZAg671iyqmJ3asQB6g',
    appId: '1:772082583953:ios:ad33cd94e94bd1745bb230',
    messagingSenderId: '772082583953',
    projectId: 'taskapp-d74d0',
    storageBucket: 'taskapp-d74d0.firebasestorage.app',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVIvFX5021PAViqZAg671iyqmJ3asQB6g',
    appId: '1:772082583953:ios:ad33cd94e94bd1745bb230',
    messagingSenderId: '772082583953',
    projectId: 'taskapp-d74d0',
    storageBucket: 'taskapp-d74d0.firebasestorage.app',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk4fn4YReYknhVgkLEGinPyHgOS7QuaR4',
    appId: '1:772082583953:web:0b8b3a21966931275bb230',
    messagingSenderId: '772082583953',
    projectId: 'taskapp-d74d0',
    authDomain: 'taskapp-d74d0.firebaseapp.com',
    storageBucket: 'taskapp-d74d0.firebasestorage.app',
    measurementId: 'G-9SKQGNGGDL',
  );
}
